# Generated by Django 4.0.4 on 2022-05-12 21:33
from datetime import datetime
from django.db import migrations, models
from uuid import uuid4
from django.db.migrations.state import StateApps
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor


def insert_initial_fees(apps: StateApps, schema_editor: DatabaseSchemaEditor):
    fees = apps.get_model("fees", "Fees")

    fee = {
        "id": uuid4(),
        "credit_fee": "0.06",
        "debit_fee": "0.04",
        "created_at": datetime.now(),
    }

    fees.objects.create(**fee)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("credit_fee", models.CharField(max_length=125)),
                ("debit_fee", models.CharField(max_length=125)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(insert_initial_fees),
    ]
