# Generated by Django 4.0.4 on 2022-05-13 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=125)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
